### ISSUE TITLE
pretrain checkpoints SLM_checkpoints.zip的链接出问题了

### ISSUE THREAD

**Issue by LY080835** [xiaoyuan1996/SemanticLocalizationMetrics#3]
![屏幕截图 2022-10-26 171628](https://user-images.githubusercontent.com/55277222/197989279-27ec3d28-87a8-4c83-8ba3-084e2608afd8.jpg)
pretrain checkpoints SLM_checkpoints.zip 和  test images SLM_testimgs.zip 的谷歌网盘是相同的链接。pretrain checkpoints SLM_checkpoints.zip真实链接缺失。
麻烦可以补充一下吗？

**Comment by xiaoyuan1996** [comment]
Sorry for the late reply. We have already updated it to AMFMN.tar, thanks for your attention.
